export interface RecallCase {
  id: string;
  category: "direct" | "paraphrase" | "cross-topic" | "multi-hop" | "fuzzy";
  query: string;
  relevantPaths: readonly string[];
  expectedTags?: readonly string[];
}

export const RECALL_DEMO_CORPUS_PATHS = [
  "work/sprint-retro.mdx",
  "work/incident-follow-up.mdx",
  "work/release-checklist.mdx",
  "work/api-decision.mdx",
  "work/focus-routine.mdx",
  "work/remote-work-setup.mdx",
  "work/mentorship-notes.mdx",
  "learning/javascript-performance.mdx",
  "learning/sql-indexing.mdx",
  "learning/spaced-repetition.mdx",
  "learning/quantum-notes.mdx",
  "learning/chinese-reading.mdx",
  "learning/photography-basics.mdx",
  "learning/statistics-notes.mdx",
  "health/sleep-routine.mdx",
  "health/strength-training.mdx",
  "health/breakfast-planning.mdx",
  "health/running-knee-care.mdx",
  "health/annual-checkup.mdx",
  "health/stress-recovery.mdx",
  "travel/yunnan-itinerary.mdx",
  "travel/kyoto-morning-route.mdx",
  "travel/train-booking.mdx",
  "travel/coastal-weekend.mdx",
  "travel/travel-packing.mdx",
  "travel/high-altitude-prep.mdx",
  "finance/index-investing.mdx",
  "finance/monthly-budget.mdx",
  "finance/emergency-fund.mdx",
  "finance/insurance-review.mdx",
  "finance/tax-prep.mdx",
  "finance/laptop-purchase.mdx",
  "home/office-plants.mdx",
  "home/coffee-brewing.mdx",
  "home/cat-food-notes.mdx",
  "home/kitchen-storage.mdx",
  "home/home-network.mdx",
  "home/apartment-repair.mdx",
  "relationships/family-gathering.mdx",
  "relationships/gift-ideas.mdx",
  "relationships/friend-trip.mdx",
  "relationships/communication-notes.mdx",
  "relationships/birthday-planning.mdx",
  "relationships/neighbor-help.mdx",
  "creative/writing-outline.mdx",
  "creative/music-practice.mdx",
  "creative/reading-list.mdx",
  "creative/photo-project.mdx",
  "creative/weekend-cooking.mdx",
  "creative/language-practice.mdx",
] as const;

export const RECALL_CASES: readonly RecallCase[] = [
  {
    id: "q01",
    category: "direct",
    query: "为什么 API 写入要采用幂等 upsert？",
    relevantPaths: ["work/api-decision.mdx"],
    expectedTags: ["API", "幂等"],
  },
  {
    id: "q02",
    category: "direct",
    query: "发布前需要检查哪些迁移、回滚和监控项目？",
    relevantPaths: ["work/release-checklist.mdx"],
    expectedTags: ["发布", "回滚"],
  },
  {
    id: "q03",
    category: "direct",
    query: "睡前有哪些能帮助我减少失眠的固定步骤？",
    relevantPaths: ["health/sleep-routine.mdx"],
    expectedTags: ["睡眠", "恢复"],
  },
  {
    id: "q04",
    category: "direct",
    query: "大理丽江五天旅行怎么安排交通和路线？",
    relevantPaths: ["travel/yunnan-itinerary.mdx"],
    expectedTags: ["云南旅行", "交通"],
  },
  {
    id: "q05",
    category: "direct",
    query: "宽基指数定投时应该遵守哪些纪律？",
    relevantPaths: ["finance/index-investing.mdx"],
    expectedTags: ["指数投资", "定投"],
  },
  {
    id: "q06",
    category: "direct",
    query: "办公室光线不够时绿萝和多肉怎么养？",
    relevantPaths: ["home/office-plants.mdx"],
    expectedTags: ["植物", "光线"],
  },
  {
    id: "q07",
    category: "paraphrase",
    query: "怎样让前端页面打开更快并减少首屏负担？",
    relevantPaths: ["learning/javascript-performance.mdx"],
    expectedTags: ["性能优化", "首屏"],
  },
  {
    id: "q08",
    category: "paraphrase",
    query: "把复习安排成隔一段时间再回看的方法是什么？",
    relevantPaths: ["learning/spaced-repetition.mdx"],
    expectedTags: ["间隔重复", "复习"],
  },
  {
    id: "q09",
    category: "paraphrase",
    query: "体重偏大时，哪些有氧运动对膝盖更友好？",
    relevantPaths: ["health/running-knee-care.mdx"],
    expectedTags: ["膝盖", "运动"],
  },
  {
    id: "q10",
    category: "paraphrase",
    query: "避开游客高峰，京都早晨适合走哪条路线？",
    relevantPaths: ["travel/kyoto-morning-route.mdx"],
    expectedTags: ["京都旅行", "早晨路线"],
  },
  {
    id: "q11",
    category: "paraphrase",
    query: "每月如何先留出安全垫再安排消费？",
    relevantPaths: ["finance/monthly-budget.mdx", "finance/emergency-fund.mdx"],
    expectedTags: ["预算", "应急金"],
  },
  {
    id: "q12",
    category: "paraphrase",
    query: "挑猫粮时应先看配料表中的哪些成分？",
    relevantPaths: ["home/cat-food-notes.mdx"],
    expectedTags: ["猫咪", "食物"],
  },
  {
    id: "q13",
    category: "cross-topic",
    query: "手冲咖啡的准备如何服务于早晨专注工作？",
    relevantPaths: ["home/coffee-brewing.mdx", "work/focus-routine.mdx"],
    expectedTags: ["咖啡", "专注"],
  },
  {
    id: "q14",
    category: "cross-topic",
    query: "远程办公怎样避免工作压力侵占恢复时间？",
    relevantPaths: ["work/remote-work-setup.mdx", "health/stress-recovery.mdx"],
    expectedTags: ["远程办公", "压力恢复"],
  },
  {
    id: "q15",
    category: "cross-topic",
    query: "想做周末摄影项目，先补哪些光线知识？",
    relevantPaths: ["creative/photo-project.mdx", "learning/photography-basics.mdx"],
    expectedTags: ["摄影", "光线"],
  },
  {
    id: "q16",
    category: "cross-topic",
    query: "高原旅行前怎样把车票、行李和防高反准备串起来？",
    relevantPaths: [
      "travel/train-booking.mdx",
      "travel/travel-packing.mdx",
      "travel/high-altitude-prep.mdx",
    ],
    expectedTags: ["高原旅行", "行李"],
  },
  {
    id: "q17",
    category: "multi-hop",
    query: "买新电脑前，如何判断预算是否会破坏应急金？",
    relevantPaths: ["finance/emergency-fund.mdx", "finance/laptop-purchase.mdx"],
    expectedTags: ["应急金", "电脑购买"],
  },
  {
    id: "q18",
    category: "multi-hop",
    query: "怎样把长期学习计划拆成可持续、可衡量的复习节奏？",
    relevantPaths: ["learning/spaced-repetition.mdx", "learning/statistics-notes.mdx"],
    expectedTags: ["学习计划", "复习"],
  },
  {
    id: "q19",
    category: "multi-hop",
    query: "为家人安排聚会和礼物时，之前记录过哪些偏好？",
    relevantPaths: ["relationships/family-gathering.mdx", "relationships/gift-ideas.mdx"],
    expectedTags: ["家庭", "礼物"],
  },
  {
    id: "q20",
    category: "multi-hop",
    query: "周末想做饭、喝咖啡又见朋友，如何安排不打乱作息？",
    relevantPaths: [
      "home/coffee-brewing.mdx",
      "creative/weekend-cooking.mdx",
      "relationships/friend-trip.mdx",
    ],
    expectedTags: ["周末", "朋友"],
  },
  {
    id: "q21",
    category: "fuzzy",
    query: "我记得有一篇笔记提到让家里网络别总断。",
    relevantPaths: ["home/home-network.mdx"],
    expectedTags: ["家庭网络", "故障排查"],
  },
  {
    id: "q22",
    category: "fuzzy",
    query: "上次想找一个不贵、能长期坚持的运动安排。",
    relevantPaths: ["health/strength-training.mdx", "health/running-knee-care.mdx"],
    expectedTags: ["运动", "习惯"],
  },
  {
    id: "q23",
    category: "fuzzy",
    query: "之前记过猫和植物都需要怎样的日常照料？",
    relevantPaths: ["home/cat-food-notes.mdx", "home/office-plants.mdx"],
    expectedTags: ["日常照料"],
  },
  {
    id: "q24",
    category: "fuzzy",
    query: "有没有记录过如何把一次事故复盘成下一次发布清单？",
    relevantPaths: ["work/incident-follow-up.mdx", "work/release-checklist.mdx"],
    expectedTags: ["事故复盘", "发布"],
  },
];
